syntax = "proto3";
package logi.protocol.axis_response_curve;
import "logi/protocol/axis.proto";

enum EnabledFlags {
  DISABLED = 0;
  WHEEL = 1;
  HANDBRAKE = 2;
  ACCELERATOR = 4;
  BRAKE = 8;
  CLUTCH = 16;
}
message Point {
  uint32 x = 1;
  uint32 y = 2;
}
message ResponseCurve {
  uint32 axis_index = 1;
  repeated logi.protocol.axis_response_curve.Point points = 2;
}
message Properties {
  logi.protocol.axis.Type axis_type = 1;
}
message AxisInfo {
  uint32 axis_index = 1;
  uint32 hid_page = 2;
  uint32 hid_usage = 3;
  uint32 axis_resolution = 4;
  uint32 points_count = 5;
  uint32 max_point_count = 6;
  logi.protocol.axis_response_curve.Properties properties = 7;
}
message Sensitivity {
  logi.protocol.axis.Id axis_id = 1;
  uint32 value = 2;
}
message EditorSettings {
  enum CurveType {
    BEZIER = 0;
    CATMULLROM = 1;
  }
  logi.protocol.axis_response_curve.EditorSettings.CurveType curve = 1;
  logi.protocol.axis.DeadZone dead_zone = 2;
  repeated logi.protocol.axis_response_curve.Point control_points = 3;
}
message MemoryUpdate {
  enum Status {
    SUCCESS = 0;
    HWERROR = 1;
    WAITING = 2;
    TIMEOUT = 3;
    ACCEPTED = 4;
    REJECTED = 5;
  }
  logi.protocol.axis.Id axis_id = 1;
  logi.protocol.axis_response_curve.MemoryUpdate.Status status = 2;
}
message CommandResult {
  message Result {
    logi.protocol.axis.Id axis_id = 1;
    string status = 2;
  }
  repeated logi.protocol.axis_response_curve.CommandResult.Result results = 1;
}
