syntax = "proto3";
package logi.protocol.display;

message Capabilities {
  bool has_display_orientation = 1;
  bool has_display_brightness = 2;
  bool has_display_mascot = 3;
  bool has_display_assets = 4;
}
message Display {
  enum Control {
    INVALID_CONTROL = 0;
    LOCAL = 1;
    AUTOMATIC = 2;
    HOST = 3;
  }
  message Orientation {
    enum Type {
      INVALID_TYPE = 0;
      UP = 1;
      DOWN = 2;
      LEFT = 3;
      RIGHT = 4;
    }
    message Info {
      repeated logi.protocol.display.Display.Orientation.Type capabilities = 1;
      bool overridable = 2;
    }
    message Params {
      logi.protocol.display.Display.Orientation.Type type = 1;
      logi.protocol.display.Display.Control control = 2;
    }
  }
  message Brightness {
    message Info {
      uint32 levels = 1;
      bool overridable = 2;
    }
    message Params {
      uint32 level = 1;
      logi.protocol.display.Display.Control control = 2;
    }
  }
  message Mascot {
    enum State {
      INVALID_STATE = 0;
      NORMAL = 1;
      IDLE = 2;
      MUTED = 3;
      CLIPPING = 4;
      HIGH = 5;
    }
    message Info {
      repeated uint32 onboard_indexes = 1;
      repeated uint32 customizable_indexes = 2;
      repeated logi.protocol.display.Display.Mascot.State states = 3;
      uint32 max_name_length = 4;
    }
    message AssetIndexes {
      repeated uint32 indexes = 1;
    }
    message Name {
      uint32 index = 1;
      string name = 2;
    }
    bool read_only = 1;
    uint32 index = 2;
  }
  message Asset {
    enum Format {
      INVALID_FORMAT = 0;
      BITMAP_565 = 1;
      BITMAP_323 = 2;
      JPEG = 3;
    }
    enum State {
      INVALID_STATE = 0;
      AVAILABLE = 1;
      ERASING = 2;
      ERASED = 3;
      PARTIAL = 4;
      APPLY_PENDING = 5;
    }
    message Info {
      uint32 index = 1;
      repeated logi.protocol.display.Display.Asset.Format formats = 2;
      uint32 max_size = 3;
      uint32 width = 4;
      uint32 height = 5;
      bool read_only = 6;
    }
    message File {
      string path = 1;
      string digest = 2;
      uint32 size = 3;
      uint32 crc = 4;
    }
    message Raw {
      string data = 1;
      uint32 crc = 2;
      string digest = 3;
    }
    uint32 index = 1;
    logi.protocol.display.Display.Asset.Format format = 2;
    logi.protocol.display.Display.Asset.State state = 3;
    logi.protocol.display.Display.Asset.File file = 4;
    logi.protocol.display.Display.Asset.Raw raw = 5;
  }
  message MascotPreset {
    message StateAsset {
      logi.protocol.display.Display.Mascot.State state = 1;
      logi.protocol.display.Display.Asset asset = 2;
    }
    string id = 1;
    string name = 2;
    logi.protocol.display.Display.Mascot mascot = 3;
    repeated logi.protocol.display.Display.MascotPreset.StateAsset assets = 4;
  }
  message MascotPresetList {
    string active_id = 1;
    repeated logi.protocol.display.Display.MascotPreset presets = 2;
  }
  message MascotPresetNameUpdate {
    string id = 1;
    string name = 2;
  }
}
