syntax = "proto3";
package logi.protocol.iprofile;

message Data {
  string uuid = 1;
  uint32 checksum = 2;
  string profile_id = 3;
}
message DataSync {
  enum Action {
    ACTION_INVALID = 0;
    DISCARD = 1;
    STORE = 2;
  }
  logi.protocol.iprofile.DataSync.Action action = 1;
  string profile_id = 2;
}
message ImportedProfile {
  string profile_name = 1;
  string profile_id = 2;
}
message OnboardProfileState {
  enum Type {
    TYPE_INVALID = 0;
    ONBOARD = 1;
    VOLATILE = 2;
  }
  enum State {
    STATE_INVALID = 0;
    INACTIVE = 1;
    ACTIVATING = 2;
    ACTIVE = 3;
  }
  logi.protocol.iprofile.OnboardProfileState.Type type = 1;
  logi.protocol.iprofile.OnboardProfileState.State state = 2;
  string profile_id = 3;
  string profile_name = 4;
}
message OnboardProfileList {
  repeated logi.protocol.iprofile.OnboardProfileState profiles = 1;
}
message OnboardStoreRequest {
  string profile_id = 1;
  string profile_name = 2;
  bool activate_profile = 3;
}
message OnboardProfileNameUpdate {
  message Profile {
    string id = 1;
    string name = 2;
  }
  repeated logi.protocol.iprofile.OnboardProfileNameUpdate.Profile profiles = 1;
}
