syntax = "proto3";
package logi.protocol.keyboard;

message Keyboard {
  enum Layout {
    INVALID_LAYOUT = 0;
    US = 1;
    INTERNATIONAL = 2;
    UK = 3;
    GERMAN = 4;
    FRENCH = 5;
    RUSSIAN = 6;
    NORDIC = 7;
    KOREAN = 8;
    JAPANESE = 9;
    CHINESE = 10;
    SWISS = 11;
    TURKISH = 12;
    SPANISH = 13;
    ITALIAN = 14;
    THAI = 15;
    INTERNATIONAL_2 = 16;
    BELGIAN = 17;
    PORTUGUESE = 18;
    PORTUGUESE_BRAZILIAN = 19;
    ARABIC = 20;
    UKRAINIAN = 21;
    HUNGARY = 22;
    CZECH = 23;
    FARSI = 24;
    RUSSIAN_ISO = 25;
    BIJOY = 26;
    JAPANESE_INTERNATIONAL = 27;
    KOREAN_ANSI = 28;
    GERMAN_GS_CERTIFIED = 29;
    CROATIAN_SLOVENIAN = 30;
    CZECH_SLOVAKIAN = 31;
    HINDI = 32;
    BULGARIAN = 33;
    HEBREW = 34;
    GREEK = 35;
  }
  enum GKeyLayout {
    INVALID_GKEY_LAYOUT = 0;
    GKEY_LEFT_COLUMN_5 = 1;
    GKEY_LEFT_COLUMN_5_TOP_ROW_4 = 2;
    GKEY_LEFT_COLUMN_6 = 3;
    GKEY_FUNCTION_KEYS_ROW_12 = 4;
  }
  enum KeyboardSize {
    UNKNOWN = 0;
    SIZE_60 = 1;
    SIZE_TKL = 2;
    SIZE_FULL = 3;
    SIZE_75 = 4;
    SIZE_98 = 5;
  }
}
message FnInverted {
  bool inversion_state = 1;
  bool default_state = 2;
  uint32 host_index = 3;
  uint32 capability_mask = 4;
}
message DisableKeys {
  repeated uint32 hid_usages = 1;
  uint32 max_disabled_keys = 2;
  repeated uint32 static_usages = 3;
}
message DisableControls {
  string preset_id = 1;
}
message DisableControlsPreset {
  repeated uint32 controls = 1;
}
message GameMode {
  bool enabled = 1;
  bool locked = 2;
}
message GameModeSupport {
  bool supported = 1;
  bool lock_supported = 2;
}
