syntax = "proto3";
package logi.protocol.scarif;
import "logi/protocol/cards.proto";
import "logi/protocol/profiles.proto";
import "logi/protocol/devices.proto";
import "logi/protocol/input_preset.proto";
import "logi/protocol/macros.proto";
import "logi/protocol/mouse.proto";

message UserPrompt {
  string type = 1;
}
message Status {
  bool enabled = 1;
  bool needs_updating = 2;
  bool user_prompted = 3;
  string version_number = 4;
  bool archive_successful_requests = 5;
  bool indent_json = 6;
  uint32 delay_requests_msecs = 7;
  logi.protocol.scarif.UserPrompt pending_user_prompt = 8;
  logi.protocol.scarif.UserPrompt scheduled_user_prompt = 9;
  string host_id = 10;
  string region = 11;
}
message SupportedTaxonomy {
  message List {
    repeated logi.protocol.scarif.SupportedTaxonomy supported_settings = 1;
  }
  string setting = 1;
  bool supported = 2;
}
message Event {
  enum Category {
    INVALID = 0;
    APP = 1;
    CONFIG = 2;
    DEVICE = 3;
    SETUP = 4;
    UI = 5;
    SETTING = 6;
    ACTION = 7;
    STATUS = 8;
    RATING = 9;
    USAGE = 10;
    DEVICE_SETTING = 11;
    REPORT = 12;
    RECOMMENDATION = 13;
    PII = 14;
  }
  logi.protocol.scarif.Event.Category category = 1;
  string id = 2;
  string data = 3;
  string sessid_ui = 4;
}
message Events {
  repeated logi.protocol.scarif.Event events = 1;
}
message ModifiedCards {
  logi.protocol.cards.Card new_card = 1;
  logi.protocol.cards.Card existing_card = 2;
}
message ProfileSlotsMap {
  logi.protocol.profiles.Profile profile = 1;
  repeated string slot_ids = 2;
}
message ImpactedProfileSlotsList {
  repeated logi.protocol.scarif.ProfileSlotsMap profile_slots_list = 1;
}
message ModifiedAssignment {
  logi.protocol.scarif.ModifiedCards modified_cards = 1;
  logi.protocol.scarif.ProfileSlotsMap profile_slots_map = 2;
}
message OnboardModeInfo {
  logi.protocol.devices.Device.Info device_info = 1;
  bool enabled = 2;
}
message DeviceDisconnect {
  logi.protocol.devices.Device.Info previous_info = 1;
  logi.protocol.devices.Device.Info current_info = 2;
}
message FeatureTriggerInfo {
  enum TriggerSource {
    UNKNOWN = 0;
    APP = 1;
    KNOB = 2;
  }
  enum FeatureID {
    UNDEFINED = 0;
    REPORT_RATE = 1;
  }
  string device_signature = 1;
  logi.protocol.scarif.FeatureTriggerInfo.TriggerSource trigger_source = 2;
  logi.protocol.scarif.FeatureTriggerInfo.FeatureID feature_id = 3;
}
message IntegrationStatus {
  string id = 1;
  string name = 2;
  bool enabled = 3;
}
message CameraUse {
  string camera_symlink = 1;
  bool in_use = 2;
  string current_application = 3;
}
message InputPresetData {
  string model_id = 1;
  string preset_id = 2;
  string profile_id = 3;
  uint32 duration_ms = 4;
  bool read_only = 5;
  string layer_name = 6;
}
message AudioUsage {
  string device_id = 1;
  uint32 process_id = 2;
  bool audio_in_use = 3;
}
message BroadcastedEvent {
  enum Type {
    UNKNOWN = 0;
    ANALYTIC_EVENT_ADDED = 1;
    BATCH_EVENTS_SUBMITTED = 2;
    BATCH_EVENTS_DELETED = 3;
    BATCH_EVENTS_QUEUED = 4;
  }
  message AnalyticEventAdded {
    message EventData {
      map<string, string> batch = 1;
      map<string, string> event = 2;
    }
    string group_id = 1;
    string event_id = 2;
    logi.protocol.scarif.BroadcastedEvent.AnalyticEventAdded.EventData event_data = 3;
    bool saved = 4;
    bool added = 5;
    string message = 6;
  }
  message BatchEventsSubmitted {
    message ErrorDetails {
      string details = 1;
      string error = 2;
      map<string, string> event = 3;
    }
    string job_id = 1;
    string group_id = 2;
    repeated string discarded_event_ids = 3;
    repeated logi.protocol.scarif.BroadcastedEvent.BatchEventsSubmitted.ErrorDetails errors = 4;
  }
  message BatchEventsDeleted {
    message FailureInfo {
      string event_id = 1;
      string file_path = 2;
      string reason = 3;
    }
    message SuccessInfo {
      string event_id = 1;
      string file_path = 2;
    }
    string job_id = 1;
    string group_id = 2;
    repeated logi.protocol.scarif.BroadcastedEvent.BatchEventsDeleted.FailureInfo failures = 3;
    repeated logi.protocol.scarif.BroadcastedEvent.BatchEventsDeleted.SuccessInfo successes = 4;
  }
  message BatchEventsQueued {
    string job_id = 1;
    string group_id = 2;
    repeated string event_ids = 3;
  }
  logi.protocol.scarif.BroadcastedEvent.Type event_type = 1;
  logi.protocol.scarif.BroadcastedEvent.AnalyticEventAdded analytic_event_added = 2;
  logi.protocol.scarif.BroadcastedEvent.BatchEventsSubmitted batch_events_submitted = 3;
  logi.protocol.scarif.BroadcastedEvent.BatchEventsDeleted batch_events_deleted = 4;
  logi.protocol.scarif.BroadcastedEvent.BatchEventsQueued batch_events_queued = 5;
}
message CommunityActionInfo {
  message CommunityData {
    int64 duration_in_ms = 1;
    string entity_category = 2;
    bool include_all_macros = 3;
    bool is_public = 4;
  }
  string action = 1;
  logi.protocol.scarif.CommunityActionInfo.CommunityData data = 2;
}
message Migration {
  string name = 1;
  string id = 2;
  string process = 3;
  string status = 4;
  string error = 5;
}
message WebcamPreset {
  logi.protocol.devices.Device.Info device_info = 1;
  logi.protocol.cards.Card card = 2;
  string trigger = 3;
}
message PageEnter {
  string id = 1;
  string pgname = 2;
  string elemname = 3;
  logi.protocol.devices.Device.Info device_info = 4;
}
message KeyswapInfo {
  map<uint32, bool> swapped_keys = 1;
  bool is_scan_triggered_from_ui = 2;
  string device_id = 3;
}
message SystemTrayMenu {
  string section_name = 1;
  string section_detail = 2;
}
message OnboardMemorySensitivityInfo {
  string device_id = 1;
  logi.protocol.mouse.Settings mouse_settings = 2;
  string profile_name = 3;
  int32 slot_no = 4;
}
