syntax = "proto3";
package logi.protocol.scroll_wheel;

message ScrollWheelConfiguration {
  string scroll_wheel_preset_id = 1;
}
message ScrollWheelPreset {
  enum WheelMode {
    WHEEL_MODE_RATCHET = 0;
    WHEEL_MODE_FREESPIN = 1;
  }
  uint32 auto_disengage_speed = 1;
  bool smartshift = 2;
  logi.protocol.scroll_wheel.ScrollWheelPreset.WheelMode mode = 3;
  uint32 tunable_torque = 4;
}
message ScrollWheelSupport {
  message SmartshiftConfiguration {
    uint32 min = 1;
    uint32 max = 2;
    uint32 step = 3;
  }
  uint32 max_tunable_torque = 2;
  logi.protocol.scroll_wheel.ScrollWheelSupport.SmartshiftConfiguration smartshift = 3;
}
