syntax = "proto3";
package logi.protocol.webcam;
import "logi/protocol/audio.proto";
import "logi/common_protocol/util.proto";

message Webcam {
  enum Mode {
    INVALID = 0;
    AUTO = 1;
    MANUAL = 2;
    BOTH = 3;
  }
  enum AutoExposurePriority {
    PRIORITY_INVALID = 0;
    PRIORITY_FRAME_RATE = 1;
    PRIORITY_EXPOSURE = 2;
  }
  enum AudioMode {
    INVALID_MODE = 0;
    MONO = 1;
    STEREO = 2;
  }
  message array {
    repeated uint32 values = 1;
  }
  message ValueSet {
    int32 value = 1;
    int32 mac = 2;
    int32 win = 3;
  }
  message CustomValues {
    repeated logi.protocol.webcam.Webcam.ValueSet custom_values = 1;
  }
  message AutoFramingList {
    repeated logi.protocol.webcam.Webcam.AutoFraming.FramingSpeed speed = 1;
    repeated logi.protocol.webcam.Webcam.AutoFraming.FramingLevel level = 2;
  }
  message Capability {
    int32 default = 1;
    logi.protocol.webcam.Webcam.Mode mode = 2;
    logi.protocol.util.RangeInt range = 3;
    logi.protocol.webcam.Webcam.CustomValues value_map = 4;
    logi.protocol.webcam.Webcam.array list = 5;
    logi.protocol.webcam.Webcam.AutoFramingList auto_framing_list = 6;
  }
  message CameraCapability {
    logi.protocol.webcam.Webcam.Capability pan = 1;
    logi.protocol.webcam.Webcam.Capability tilt = 2;
    logi.protocol.webcam.Webcam.Capability roll = 3;
    logi.protocol.webcam.Webcam.Capability zoom = 4;
    logi.protocol.webcam.Webcam.Capability exposure = 5;
    logi.protocol.webcam.Webcam.Capability iris = 6;
    logi.protocol.webcam.Webcam.Capability focus = 7;
    repeated uint32 fov = 8;
    bool hdr = 9;
    bool audio_mode = 10;
    bool stabilization = 11;
    bool orientation = 12;
  }
  message VideoCapability {
    logi.protocol.webcam.Webcam.Capability brightness = 1;
    logi.protocol.webcam.Webcam.Capability contrast = 2;
    logi.protocol.webcam.Webcam.Capability hue = 3;
    logi.protocol.webcam.Webcam.Capability saturation = 4;
    logi.protocol.webcam.Webcam.Capability sharpness = 5;
    logi.protocol.webcam.Webcam.Capability gamma = 6;
    logi.protocol.webcam.Webcam.Capability color_enabled = 7;
    logi.protocol.webcam.Webcam.Capability white_balance = 8;
    logi.protocol.webcam.Webcam.Capability gain = 9;
    repeated uint32 anti_flicker_values = 10;
  }
  message Capabilities {
    logi.protocol.webcam.Webcam.CameraCapability camera = 1;
    logi.protocol.webcam.Webcam.VideoCapability video = 2;
  }
  message Setting {
    int32 value = 1;
    logi.protocol.webcam.Webcam.Mode mode = 2;
  }
  message CameraSettings {
    enum CameraPriority {
      INVALID = 0;
      FRAME_RATE = 1;
      EXPOSURE = 2;
    }
    enum AudioMode {
      INVALID_MODE = 0;
      MONO = 1;
      STEREO = 2;
    }
    logi.protocol.webcam.Webcam.CameraSettings.CameraPriority priority = 1;
    bool hdr = 2;
    uint32 fov = 3;
    logi.protocol.webcam.Webcam.Setting pan = 4;
    logi.protocol.webcam.Webcam.Setting tilt = 5;
    logi.protocol.webcam.Webcam.Setting roll = 6;
    logi.protocol.webcam.Webcam.Setting zoom = 7;
    logi.protocol.webcam.Webcam.Setting exposure = 8;
    logi.protocol.webcam.Webcam.Setting iris = 9;
    logi.protocol.webcam.Webcam.Setting focus = 10;
    logi.protocol.webcam.Webcam.CameraSettings.AudioMode audio_mode = 11;
    bool stabilization = 12;
  }
  message VideoSettings {
    uint32 anti_flicker = 1;
    logi.protocol.webcam.Webcam.Setting brightness = 2;
    logi.protocol.webcam.Webcam.Setting contrast = 3;
    logi.protocol.webcam.Webcam.Setting hue = 4;
    logi.protocol.webcam.Webcam.Setting saturation = 5;
    logi.protocol.webcam.Webcam.Setting sharpness = 6;
    logi.protocol.webcam.Webcam.Setting gamma = 7;
    logi.protocol.webcam.Webcam.Setting color = 8;
    logi.protocol.webcam.Webcam.Setting white_balance = 9;
    logi.protocol.webcam.Webcam.Setting gain = 10;
  }
  message BroadcastMode {
    bool value = 1;
    string device_id = 2;
  }
  message Orientation {
    enum Mode {
      INVALID_ORIENTATION = 0;
      PORTRAIT_UP = 1;
      PORTRAIT_DOWN = 2;
      LANDSCAPE_LEFT = 3;
      LANDSCAPE_RIGHT = 4;
    }
    logi.protocol.webcam.Webcam.Orientation.Mode orientation = 1;
  }
  message AutoFraming {
    enum FramingSpeed {
      FRAMING_SPEED_DEFAULT = 0;
      FRAMING_SPEED_SLOWER = 1;
      FRAMING_SPEED_FASTER = 2;
    }
    enum FramingLevel {
      FRAMING_LEVEL_DEFAULT = 0;
      FRAMING_LEVEL_CLOSER = 1;
      FRAMING_LEVEL_FARTHER = 2;
    }
    bool enabled = 1;
    logi.protocol.webcam.Webcam.AutoFraming.FramingSpeed framing_speed = 2;
    logi.protocol.webcam.Webcam.AutoFraming.FramingLevel framing_level = 3;
  }
  message CropSettings {
    message RightSight {
      bool enabled = 1;
    }
    logi.protocol.webcam.Webcam.Setting pan = 1;
    logi.protocol.webcam.Webcam.Setting tilt = 2;
    logi.protocol.webcam.Webcam.Setting zoom = 3;
    uint32 fov = 4;
    bool show_mode = 5;
    bool manual_card = 6;
    logi.protocol.webcam.Webcam.CropSettings.RightSight right_sight = 7;
    logi.protocol.webcam.Webcam.AutoFraming auto_framing = 8;
  }
  message ExposureSettings {
    logi.protocol.webcam.Webcam.Setting exposure = 1;
    uint32 exposure_compensation = 2;
    logi.protocol.webcam.Webcam.Setting gain = 3;
    bool hdr = 4;
    logi.protocol.webcam.Webcam.AutoExposurePriority priority = 5;
    bool manual_card = 6;
  }
  message ImageSettings {
    logi.protocol.webcam.Webcam.Setting brightness = 1;
    logi.protocol.webcam.Webcam.Setting contrast = 2;
    logi.protocol.webcam.Webcam.Setting saturation = 3;
    logi.protocol.webcam.Webcam.Setting sharpness = 4;
    uint32 tint = 5;
    uint32 vibrance = 6;
    logi.protocol.webcam.Webcam.Setting white_balance = 7;
    uint32 temperature_compensation = 8;
    bool manual_card = 9;
  }
  message FocusSettings {
    logi.protocol.webcam.Webcam.Setting focus = 1;
    bool manual_card = 2;
  }
  message DeepSettings {
    uint32 anti_flicker = 1;
    bool video_stabilization = 2;
    logi.protocol.webcam.Webcam.AudioMode audio_mode = 3;
    logi.protocol.webcam.Webcam.VideoPreviewSettings video_preview = 4;
    bool stop_video_on_app_focus_loss = 5;
    string snapshot_path = 6;
  }
  message MicrophoneSettings {
    logi.protocol.webcam.Webcam.AudioMode audio_mode = 1;
    logi.protocol.audio.Volume volume = 2;
    logi.protocol.webcam.Webcam.AudioLibraryMode audio_library_mode = 3;
  }
  message CropCapability {
    logi.protocol.webcam.Webcam.Capability pan = 1;
    logi.protocol.webcam.Webcam.Capability tilt = 2;
    logi.protocol.webcam.Webcam.Capability zoom = 3;
    logi.protocol.webcam.Webcam.Capability fov = 4;
    logi.protocol.webcam.Webcam.Capability show_mode = 5;
    bool has_pan_and_tilt_on_min_zoom = 6;
    bool has_rightsight_support = 7;
    logi.protocol.webcam.Webcam.Capability auto_framing = 8;
  }
  message ExposureCapability {
    logi.protocol.webcam.Webcam.Capability exposure = 1;
    logi.protocol.webcam.Webcam.Capability exposure_compensation = 2;
    logi.protocol.webcam.Webcam.Capability gain = 3;
    logi.protocol.webcam.Webcam.Capability hdr = 4;
    logi.protocol.webcam.Webcam.Capability priority = 5;
  }
  message ImageCapability {
    logi.protocol.webcam.Webcam.Capability brightness = 1;
    logi.protocol.webcam.Webcam.Capability contrast = 2;
    logi.protocol.webcam.Webcam.Capability saturation = 3;
    logi.protocol.webcam.Webcam.Capability sharpness = 4;
    logi.protocol.webcam.Webcam.Capability tint = 5;
    logi.protocol.webcam.Webcam.Capability vibrance = 6;
    logi.protocol.webcam.Webcam.Capability white_balance = 7;
    logi.protocol.webcam.Webcam.Capability temperature_compensation = 8;
  }
  message FocusCapability {
    logi.protocol.webcam.Webcam.Capability focus = 1;
  }
  message DeepCapability {
    logi.protocol.webcam.Webcam.Capability anti_flicker = 1;
    logi.protocol.webcam.Webcam.Capability video_stabilization = 2;
    logi.protocol.webcam.Webcam.VideoPreviewCapability video_preview = 3;
    logi.protocol.webcam.Webcam.Capability video_on_app_focus_loss = 4;
    string snapshot_path = 5;
  }
  message AudioLibraryModeCapability {
    logi.protocol.webcam.Webcam.Capability dynamic_audio = 1;
  }
  message AudioLibraryMode {
    bool dynamic_audio = 1;
  }
  message MicrophoneCapability {
    logi.protocol.webcam.Webcam.Capability audio_mode = 1;
    bool has_microphone_disable_support = 2;
    bool has_volume_feature = 3;
    logi.protocol.audio.Volume default_volume = 4;
    logi.protocol.webcam.Webcam.AudioLibraryModeCapability audio_library_mode = 5;
  }
  message PreviewStatusCapability {
    logi.protocol.webcam.Webcam.Capability preview_status = 1;
  }
  message Resolution {
    enum Id {
      RES_INVALID = 0;
      RES_4Kp30 = 1;
      RES_1080p60 = 2;
      RES_1080p30 = 3;
      RES_720p60 = 4;
      RES_720p30 = 5;
      RES_360p30 = 6;
      RES_240p30 = 7;
      RES_240_432p30 = 8;
      RES_2Kp30 = 9;
    }
    message ZoomLimit {
      int32 max = 1;
      int32 max_with_eis = 2;
    }
    logi.protocol.webcam.Webcam.Resolution.Id id = 1;
    logi.protocol.webcam.Webcam.Resolution.ZoomLimit zoom_limit = 2;
    bool available = 3;
  }
  message VideoPreviewSettings {
    bool grid = 1;
    bool preview = 2;
    bool mirror = 3;
    logi.protocol.webcam.Webcam.Resolution.Id resolution = 4;
  }
  message VideoPreviewCapability {
    bool hasGridSupport = 1;
    bool hasMirrorSupport = 2;
    bool hasDisablePreviewSupport = 3;
    logi.protocol.webcam.Webcam.VideoPreviewSettings default_settings = 4;
    repeated logi.protocol.webcam.Webcam.Resolution resolutions = 5;
  }
  message AllCapabilities {
    logi.protocol.webcam.Webcam.CropCapability crop = 1;
    logi.protocol.webcam.Webcam.ExposureCapability exposure = 2;
    logi.protocol.webcam.Webcam.ImageCapability image = 3;
    logi.protocol.webcam.Webcam.FocusCapability focus = 4;
    logi.protocol.webcam.Webcam.DeepCapability deep = 5;
    logi.protocol.webcam.Webcam.MicrophoneCapability microphone = 6;
    logi.protocol.webcam.Webcam.PreviewStatusCapability orientation = 7;
    bool has_hardware_reset_support = 8;
    bool has_talos_support = 9;
  }
  message Resolutions {
    repeated logi.protocol.webcam.Webcam.Resolution resolutions = 1;
  }
  message ShowModeSettings {
    string device_id = 1;
    logi.protocol.webcam.Webcam.Setting pan = 2;
    logi.protocol.webcam.Webcam.Setting tilt = 3;
    logi.protocol.webcam.Webcam.Setting zoom = 4;
    uint32 fov = 5;
    bool orientation = 6;
  }
  message StreamingStatus {
    enum MultiAppStreaming {
      INVALID = 0;
      ON = 1;
      OFF = 2;
      UNKNOWN = 3;
    }
    bool ui_stream_acquired = 1;
    bool backend_stream_acquired = 2;
    logi.protocol.webcam.Webcam.StreamingStatus.MultiAppStreaming multi_app_streaming = 3;
  }
  message CameraPresetSettings {
    logi.protocol.webcam.Webcam.CropSettings crop_settings = 1;
    logi.protocol.webcam.Webcam.ImageSettings image_settings = 2;
    logi.protocol.webcam.Webcam.ExposureSettings exposure_settings = 3;
    logi.protocol.webcam.Webcam.FocusSettings focus_settings = 4;
    bool manual_card = 5;
  }
}
