syntax = "proto3";
package logi.updater_ipc.protocol.v1.protobuf;

message EndpointInformation {
  string Name = 1;
  string Identifier = 2;
  string Version = 3;
  uint64 ProcessID = 4;
  string ExecutablePath = 5;
  uint64 start_time = 6;
}
message HelloRequest {
  logi.updater_ipc.protocol.v1.protobuf.EndpointInformation Endpoint = 1;
  string Language = 2;
  repeated uint32 SupportedProtocols = 3;
}
message HelloResponse {
  logi.updater_ipc.protocol.v1.protobuf.EndpointInformation Endpoint = 1;
  uint32 ProtocolVersion = 2;
}
message PingRequestResponse {
  uint32 Nonce = 1;
}
message GoodbyeRequest {
}
message GetConnectedClientsRequest {
}
message GetConnectedClientsResponse {
  repeated logi.updater_ipc.protocol.v1.protobuf.EndpointInformation Endpoints = 1;
}
message ConnectionStatusChangeBroadcast {
  enum ConnectionStatus {
    Connected = 0;
    Disconnected = 1;
  }
  enum Flags {
    None = 0;
    CleanDisconnect = 1;
    ProcessClosed = 2;
    LogitechSigned = 4;
  }
  logi.updater_ipc.protocol.v1.protobuf.EndpointInformation Endpoint = 1;
  logi.updater_ipc.protocol.v1.protobuf.ConnectionStatusChangeBroadcast.ConnectionStatus OldStatus = 2;
  logi.updater_ipc.protocol.v1.protobuf.ConnectionStatusChangeBroadcast.ConnectionStatus NewStatus = 3;
  logi.updater_ipc.protocol.v1.protobuf.ConnectionStatusChangeBroadcast.Flags StatusFlags = 4;
}
