syntax = "proto3";
package logi.updater_ipc.protocol.v1.protobuf;
import "google/protobuf/timestamp.proto";

enum InstallBlockerStatus {
  NO_INSTALL_BLOCKER = 0;
  HAS_INSTALL_BLOCKER = 1;
}
message updates {
  message Status {
    enum State {
      INVALID = 0;
      INITIALIZING = 1;
      NO_UPDATES = 2;
      CHECKING_FOR_UPDATES = 3;
      UPDATE_AVAILABLE = 4;
      FEATURE_KEYS_AVAILABLE = 5;
      UPDATE_DOWNLOADING = 6;
      UPDATE_UNPACKING = 7;
      UPDATE_READY = 8;
      UPDATE_INSTALLING = 9;
      RESTARTING = 10;
      DEPOTS_DOWNLOADING = 11;
      UPDATER_ERROR = 12;
      UNSUPPORTED_OS_ERROR = 13;
    }
    enum ProgressType {
      DOWNLOAD = 0;
      UNCOMPRESS = 1;
    }
    message Progress {
      float percent = 1;
      float rate = 2;
      uint64 download_size = 3;
      uint64 expected_size = 4;
      logi.updater_ipc.protocol.v1.protobuf.updates.Status.ProgressType type = 5;
    }
    logi.updater_ipc.protocol.v1.protobuf.updates.Status.State state = 1;
    logi.updater_ipc.protocol.v1.protobuf.updates.Status.Progress progress = 2;
    int32 error_code = 3;
    string error_message = 4;
    uint32 retry_countdown = 5;
  }
}
message Channel {
  string pipeline_host = 1;
  string name = 2;
  string password = 3;
  repeated string access_groups = 4;
}
message Action {
  enum Type {
    INVALID = 0;
    INSTALL = 1;
    UPDATE = 2;
    UNINSTALL = 3;
    REINSTALL = 4;
  }
  logi.updater_ipc.protocol.v1.protobuf.Action.Type type = 1;
  string app_tag = 2;
  int32 gate_id = 5;
  string version = 6;
  string old_version = 7;
  int64 download_size = 8;
  int64 install_size = 9;
}
message Actions {
  repeated logi.updater_ipc.protocol.v1.protobuf.Action actions = 1;
  bool force = 2;
  bool keep_user_settings = 3;
}
message ActionsRequest {
  string transaction_id = 1;
  repeated logi.updater_ipc.protocol.v1.protobuf.Action actions = 2;
  bool force = 3;
  bool keep_user_settings = 4;
}
message ActionsList {
  repeated logi.updater_ipc.protocol.v1.protobuf.Action actions = 1;
}
message PipelineStatus {
  map<string, logi.updater_ipc.protocol.v1.protobuf.updates.Status> pipelines = 1;
  logi.updater_ipc.protocol.v1.protobuf.updates.Status.State aggregate_state = 2;
  bool needs_reboot = 3;
  logi.updater_ipc.protocol.v1.protobuf.updates.Status.State job_state = 4;
}
message AppGateRelationships {
  repeated string requirements = 1;
  repeated string provides = 2;
  repeated string obsoletes = 3;
  repeated string conflicts = 4;
  repeated string recommends = 5;
  repeated string suggests = 6;
  repeated string enhances = 7;
  repeated string supplements = 8;
}
message AppGateInfo {
  string app_id = 1;
  int32 gate_id = 3;
  string core_depot_name = 4;
  logi.updater_ipc.protocol.v1.protobuf.AppGateRelationships relationships = 5;
}
message AppInfo {
  string name = 1;
  string app_tag = 2;
  string install_location = 3;
  uint64 size_on_disk = 4;
  uint64 pending_download_size = 5;
  string installed_gate = 6;
  string latest_gate = 7;
  repeated logi.updater_ipc.protocol.v1.protobuf.AppGateInfo gates = 8;
  bool has_launch = 9;
  int32 installed_gate_id = 10;
  int32 latest_gate_id = 11;
  string installed_version = 12;
}
message StatusRequest {
  string transaction_id = 1;
}
message AppsRequest {
  string transaction_id = 1;
}
message AppsResponse {
  repeated logi.updater_ipc.protocol.v1.protobuf.AppInfo apps = 1;
}
message AppInfoRequest {
  string app_tag = 1;
  string transaction_id = 2;
}
message GetChannelInfoRequest {
  string app_tag = 1;
  string transaction_id = 2;
}
message IsOSCompatibleRequest {
  string transaction_id = 1;
}
message IsOSCompatibleResponse {
  bool is_compatible = 1;
}
message InstallationSizeRequest {
  string transaction_id = 1;
}
message InstallationSizeResponse {
  uint64 size_on_disk = 1;
}
message SetChannelInfoRequest {
  string app_tag = 1;
  logi.updater_ipc.protocol.v1.protobuf.Channel channel = 2;
  string transaction_id = 3;
}
message CheckForUpdatesRequest {
  string transaction_id = 1;
  bool offline_only = 2;
}
message ExecuteActionsRequest {
  string transaction_id = 1;
}
message CommitActionsResponse {
}
message CommandLineEntry {
  string key = 1;
  repeated string values = 2;
}
message SaveCommandLineRequest {
  repeated logi.updater_ipc.protocol.v1.protobuf.CommandLineEntry entries = 1;
  string transaction_id = 2;
}
message CancelRequest {
  string transaction_id = 1;
}
message DownloadRequest {
  bool staged_only = 1;
  string transaction_id = 2;
}
message LaunchRequest {
  string app_tag = 1;
  string transaction_id = 2;
}
message InstallBlockerRequest {
  string transaction_id = 1;
}
message InstallBlockerResponse {
  logi.updater_ipc.protocol.v1.protobuf.InstallBlockerStatus status = 1;
  string reason = 2;
}
message CreateTransactionResponse {
  string transaction_id = 1;
}
message CloseTransactionRequest {
  string transaction_id = 1;
}
message ClaimTransactionRequest {
  string transaction_id = 1;
}
message HandoffTransactionResponse {
  string handoff_data = 1;
}
message ExecutionStatus {
  enum Status {
    INVALID = 0;
    IDLE = 1;
    PENDING = 2;
    IN_PROGRESS = 3;
    SUCCESSFUL = 4;
    ERROR = 5;
    ERROR_MISSING_APPLICATION_STORE = 6;
  }
  message ActionWithStatus {
    logi.updater_ipc.protocol.v1.protobuf.Action action = 1;
    logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus.Status status = 2;
    google.protobuf.Timestamp start = 3;
    google.protobuf.Timestamp end = 4;
  }
  message ProcessInfo {
    string id = 1;
    string name = 2;
    string version = 3;
    string path = 4;
    uint32 pid = 5;
    uint64 start_time = 6;
  }
  logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus.Status overall_status = 1;
  string transaction_id = 2;
  logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus.ProcessInfo owner_info = 3;
  logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus.ProcessInfo runner_info = 4;
  string transaction_log_path = 5;
  string handoff_data_path = 6;
  repeated logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus.ActionWithStatus actions = 7;
  bool handed_off = 8;
  bool remote = 9;
}
message ExecutionStatusEvent {
  logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus old_status = 1;
  logi.updater_ipc.protocol.v1.protobuf.ExecutionStatus new_status = 2;
}
message DirectUninstallRequest {
  string transaction_id = 1;
  string app_tag = 2;
  bool keep_user_settings = 3;
}
